package ch.bfh.game_new.entity;

public enum ObjectType {
	PHASER, PHASERBIG, MISSILE, LASER, PLAYERSHIP, ENEMYSHIP, PICKUPHEALTH, PICKUPMISSILE, PICKUPENERGY,
	UPGRADEMISSILE, UPGRADEPHASER, SPACETURRET
}
